window.weapon = [
  { weaponType: 'Простое рукопашное оружие', title: 'боевой посох', damage: '1к6 дробящий', weight: 4, properties: 'универсальное 1к8' },
  { weaponType: 'Простое рукопашное оружие', title: 'булава', damage: '1к6 дробящий', weight: 4, properties: '' },
  { weaponType: 'Простое рукопашное оружие', title: 'дубинка', damage: '1к4 дробящий', weight: 2, properties: 'лёгкое' },
  { weaponType: 'Простое рукопашное оружие', title: 'кинжал', damage: '1к4 колющий', weight: 1, properties: 'лёгкое, метательное (дис. 20/60), фехтовальное' },
  { weaponType: 'Простое рукопашное оружие', title: 'копьё', damage: '1к6 колющий', weight: 3, properties: 'метательное (дис. 20/60), универсальное (1к8) ' },
  { weaponType: 'Простое рукопашное оружие', title: 'лёгкий молот', damage: '1к4 дробящий', weight: 2, properties: 'лёгкое, метательное (дис. 20/60) ' },
  { weaponType: 'Простое рукопашное оружие', title: 'метательное копьё', damage: '1к6 колющий', weight: 2, properties: 'метательное (дис. 30/120)' },
  { weaponType: 'Простое рукопашное оружие', title: 'палица', damage: '1к8 дробящий', weight: 10, properties: 'двуручное' },
  { weaponType: 'Простое рукопашное оружие', title: 'ручной топор', damage: '1к6 рубящий', weight: 2, properties: 'лёгкое, метательное (дис. 20/60)' },
  { weaponType: 'Простое рукопашное оружие', title: 'серп', damage: '1к4', weight: 2, properties: 'лёгкое' },
  { weaponType: 'Простое дальнобойное оружие', title: 'арбалет, лёгкий', damage: '1к8 колющий', weight: 5, properties: 'боеприпас (дис. 80/320), двуручное, перезарядка' },
  { weaponType: 'Простое дальнобойное оружие', title: 'дротик', damage: '1к4 колющий', weight: 0.25, properties: 'метательное (дис. 20/60), фехтовальное' },
  { weaponType: 'Простое дальнобойное оружие', title: 'короткий лук', damage: '1к6 колющий', weight: 2, properties: 'боеприпас (дис. 80/320), двуручное' },
  { weaponType: 'Простое дальнобойное оружие', title: 'праща', damage: '1к4 дробящий', weight: 0, properties: 'боеприпас (дис. 30/120)' },
  { weaponType: 'Воинское рукопашное оружие', title: 'алебарда', damage: '1к10 рубящий', weight: 6, properties: 'двуручное, досягаемость, тяжёлое ' },
  { weaponType: 'Воинское рукопашное оружие', title: 'боевая кирка', damage: '1к8 колющий', weight: 2, properties: '' },
  { weaponType: 'Воинское рукопашное оружие', title: 'боевой молот', damage: '1к8 дробящий', weight: 2, properties: 'Универсальное (1к10)' },
  { weaponType: 'Воинское рукопашное оружие', title: 'боевой топор', damage: '1к8 рубящий', weight: 4, properties: 'Универсальное (1к10)' },
  { weaponType: 'Воинское рукопашное оружие', title: 'глефа', damage: '1к10 рубящий', weight: 6, properties: 'двуручное, досягаемость, тяжёлое' },
  { weaponType: 'Воинское рукопашное оружие', title: 'двуручный меч', damage: '2к6 рубящий', weight: 6, properties: 'двуручное, тяжёлое' },
  { weaponType: 'Воинское рукопашное оружие', title: 'длинное копьё', damage: '1к12 колющий', weight: 6, properties: 'досягаемость, особое' },
  { weaponType: 'Воинское рукопашное оружие', title: 'длинный меч', damage: '1к8 рубящий', weight: 3, properties: 'универсальное(1к10)' },
  { weaponType: 'Воинское рукопашное оружие', title: 'кнут', damage: '1к4 рубящий', weight: 3, properties: 'досягаемость, фехтовальное' },
  { weaponType: 'Воинское рукопашное оружие', title: 'короткий меч', damage: '1к6 колющий', weight: 2, properties: 'лёгкое, фехтовальное' },
  { weaponType: 'Воинское рукопашное оружие', title: 'молот', damage: '2к6 дробящий', weight: 10, properties: 'двуручное, тяжёлое' },
  { weaponType: 'Воинское рукопашное оружие', title: 'моргенштерн', damage: '1к8 колющий', weight: 4, properties: '' },
  { weaponType: 'Воинское рукопашное оружие', title: 'пика', damage: '1к10 колющий', weight: 18, properties: 'двуручное, досягаемость, тяжёлое' },
  { weaponType: 'Воинское рукопашное оружие', title: 'рапира', damage: '1к8 колющий', weight: 2, properties: 'фехтовальное' },
  { weaponType: 'Воинское рукопашное оружие', title: 'секира', damage: '1к12 рубящий', weight: 7, properties: 'двуручное, тяжёлое' },
  { weaponType: 'Воинское рукопашное оружие', title: 'скимитар', damage: '1к6 рубящий', weight: 3, properties: 'лёгкое, фехтовальное' },
  { weaponType: 'Воинское рукопашное оружие', title: 'трезубец', damage: '1к6 колющий', weight: 4, properties: 'метательное (дис. 20/60), универсальное (1к8)' },
  { weaponType: 'Воинское рукопашное оружие', title: 'цеп', damage: '1к8 рубящий', weight: 2, properties: '' },
  { weaponType: 'Воинское дальнобойное оружие', title: 'арбалет, ручной', damage: '1к6 колющий', weight: 3, properties: 'Боеприпас (дис. 30/120), лёгкое, перезарядка' },
  { weaponType: 'Воинское дальнобойное оружие', title: 'арбалет, тяжёлый', damage: '1к10 колющий', weight: 18, properties: 'Боеприпас (дис. 100/400), двуручное, перезарядка, тяжёлое' },
  { weaponType: 'Воинское дальнобойное оружие', title: 'длинный лук', damage: '1к8 колющий', weight: 2, properties: 'Боеприпас (дис. 150/600), двуручное, тяжёлое' },
  { weaponType: 'Воинское дальнобойное оружие', title: 'духовая трубка', damage: '1 колющий', weight: 1, properties: 'Боеприпас (дис. 25/100), перезарядка' },
  { weaponType: 'Воинское дальнобойное оружие', title: 'сеть', damage: 'нет урона', weight: 3, properties: 'Метательное (дис. 5/15), особое' },
  { weaponType: 'Без оружия', title: 'нет оружия', damage: '', weight: '', properties: '' }
];
